### ISSUE TITLE
NO yahoofinance in pyalgotrade.tools

### ISSUE THREAD

**Issue by Freakwill** [upbit/pyalgotrade-step-by-step#1]
```python
from pyalgotrade.tools import yahoofinance
ImportError: cannot import name 'yahoofinance'
```

**Comment by 154610393** [comment]
you should use python2 ,not python3

**Comment by Freakwill** [comment]
I translated it to 3 with 2to3, and I can't find yahoofinance in pyalgotrade.tools. Thank you for your reply

**Comment by 154610393** [comment]
or You should try installing pylagotrade-python3 0.1  by pip

**Comment by 154610393** [comment]
E:\zzw\pycharm\untitled\venv\Lib\site-packages\pyalgotrade\barfeed///////// yahoofinance
This is my path，I hope useful to you
